### ISSUE TITLE
"Metadata (name products) Does not contain one or more angles grids!"

### ISSUE THREAD

**Issue by safalabolo** [kraftek/awsdownload#2]
Dear kraftek,
Currently downloading from AWS and ESA-HUB is successful.
Unfortunately, the processing by SEN2COR of granule downloaded fails, contrary to what happens for the same granule selected from the entire acquisition (zip file) downloaded via a simple download manager.

A first warning is the message when downloading: "Metadata (name products) Does not contain one or more angles grids!"

Thanks in advance for your reply

**Comment by kraftek** [comment]
Dear safalabolo,

I am aware of this "problem". Sen2Cor checks for the structure of the product, including files that are not necessary for processing (like the ones from the HTML folder). I will modify the downloader to produce the same structure, with dummy files, so that Sen2Cor will process them.
The warning you have observed may occur for some areas. From a certain moment in time, the PDGS team decided not to include the view angles grids that contain NaN for all the values. But there are tools that require all the angles to be present. Therefore, the downloader either computes missing values from the existing ones, or fills the missing angles grids with NaN, depending on the value given to the argument "-ma" (NONE, NAN or INTERPOLATE).

**Comment by wouellette** [comment]
Safalabolo:
"Unfortunately, the processing by SEN2COR of granule downloaded fails, contrary to what happens for the same granule selected from the entire acquisition (zip file) downloaded via a simple download manager."

Your answer: "I will modify the downloader to produce the same structure, with dummy files, so that Sen2Cor will process them."

The head .xml metadata file still doesn't match the same structure as it does would you download it from the esa hub directly. It's fine if you download only one tile and do the sen2cor and subsequent processing on that one and single tile, but if you download one tile, and then some time later another one of that same image, the .SAFE folder will be completed by the new granule(s), but the head .xml file will be replaced by a metadata file referring to that new tile only.

I am trying to see what needs be done in your code, but I am unfortunately not too handy with these things.

Thanks for the effort in all cases and hope to hear back soon.
