### ISSUE TITLE
Remote path problem on AWS

### ISSUE THREAD

**Issue by Cuten** [kraftek/awsdownload#7]
Hi, I am trying this software (I think it is great) but I found an issue:

[WARNING] Cannot download http://sentinel-s2-l1c.s3.amazonaws.com/zips/S2A_MSIL1C_20161207T073302_N0204_R049_T37MEV_20161207T074604.zip

When browsing the amazon s3 bucket, it indeed seems that zips folder does not exist. Those errors ends up with an uncompleted product downloaded (not valid for SNAP)

![image](https://cloud.githubusercontent.com/assets/22741195/21226822/93993dfe-c2d7-11e6-971e-823d332e3377.png)

Might the structure at Amazon have changed?.

Thank you.

**Comment by kraftek** [comment]
Thank you for your interrest.
It seems they have removed the zips path.
I will consider this in the next update.
But, other than this, the downloaded products should be fine for SNAP. Could you please provide me with your log file?

**Comment by Cuten** [comment]
Thanks for your quick answer. I have done a new attempt using the command like this:

` java -jar ProductDownload.jar -af polygon.txt --sensor S2 --out /home/ruben/ESATESTING/awsdownload-git/ -start 2016-10-15 --store AWS --cloudpercentage 30 --limit 10 --user xxxx --password xxxx -v
`
It has generated two product downloads, but only one of them has the right xml to be opened. I have attached the full log. 

Thanks for your help.

[productdownload.log.zip](https://github.com/kraftek/awsdownload/files/661262/productdownload.log.zip)
[polygon.txt.zip](https://github.com/kraftek/awsdownload/files/661264/polygon.txt.zip)

**Comment by kraftek** [comment]
I have investigated your problem. Indeed the download returns 2 products, but none of them can be opened in SNAP. After digging a bit, it seems to be a problem in SNAP, not in the downloader. I have downloaded directly from SciHub the newer product https://scihub.copernicus.eu/dhus/odata/v1/Products('b09c2941-b070-4775-9178-e00dfec322b7')/$value and the behavior in SNAP is the same. I have created an issue for the Sentinel-2 Toolbox team so that they can take a look.
